### ISSUE TITLE
Sync is not working because of issues in spotify-client on RPI with missing support of armhf

### ISSUE THREAD

**Issue by erikp152** [maximilianvoss/spotify-toniebox-sync#1]
Hey good evening. Very nice project, which i want to use for my kinds streaming spotify-playlists via a tonie-figure. I have done the following steps:

1. Install the spotify client via "raspotify" (https://github.com/dtcooper/raspotify), because of issues like "Das Laden der konfigurierten Datei »non-free/binary-armhf/Packages« wird übersprungen, da das Depot »http://repository.spotify.com stable InRelease« die Architektur »armhf« nicht unterstützt." if i wanted to install it through your step "sudo apt-get install -y spotify-client".
Install was working fine with an easy-install method:
`curl -sL https://dtcooper.github.io/raspotify/install.sh | sh`

2. I must change your link for the repository-clone to get it installed - because it has changed
```
git clone https://github.com/maximilianvoss/spotify-toniebox-sync.git
ln -sf $PWD/spotify-toniebox-sync/bin/sp /usr/local/bin
ln -sf $PWD/spotify-toniebox-sync/bin/stream_recorder.pl /usr/local/bin/
```

3. I found all the codes I need for the property-files and generated the refreshToken

4. I did the mapping for the daemon in the properties, and started the daemon after installing maven on my RPI and bulding a jar with all dependencies.

Can you help me please on the issue regarding spotify - i guess the client is not working the same as the one you suggested and also the double-check of ? Thanks, Erik.

**Comment by maximilianvoss** [comment]
Hi Erik,
my apologies for the very late reply - was not really observing the Github notifications.
If I'm not mistaken the issue is that Spotify is not running natively on RaspberryPi. Let me investigate on this and maybe we can make it work somehow.
Keep posted.
Max
