### ISSUE TITLE
struggling with install

### ISSUE THREAD

**Issue by e5uicide** [maximilianvoss/spotify-toniebox-sync#12]
hey,
i tried to do the install step by step as you explained. but at the point "java -jar spotify-toniebox-sync-[VERSION]-jar-with-dependencies.jar --apicode" i got stuck. would you be so kind to explain what to do at this point ? i dont even know what VERSION to put in.
your tool looks great and seems to be exactly what i've been looking for, but i cant figure out how to install...

sorry for being such a noob :(

**Comment by DrRSatzteil** [comment]
Did you actually build the jar file yet as described in the Readme? If yes you should find the file with the current version number in the target folder.
