### ISSUE TITLE
Trackname

### ISSUE THREAD

**Issue by DrRSatzteil** [maximilianvoss/spotify-toniebox-sync#16]
Hi,

First of all thank you for the great work!

I have a question regarding the use of the trackname property: why doesn't the default value use the id at the start as explained in the README file? The thing is that the commit of my changed tonie fails when I use the ID but otherwise duplicate songs are uploaded. I couldn't track this issue down yet but was wondering whether this feature is really usable/complete yet or if I'm doing something wrong?!

**Comment by DrRSatzteil** [comment]
The problem was that the track name of one of my tracks exeeded the maximum length of 128 characters. I created PR #17 to address this issue.

**Comment by maximilianvoss** [comment]
The idea behind the ID prefix of the track name is to not delete files which are uploaded by hand to the Toniebox. Would be a pity to loose a reading from a grandparent or something ;) Will review the PR. in a moment
