### ISSUE TITLE
Set a User-Agent HTTP header

### ISSUE THREAD

**Issue by phihag** [maximilianvoss/spotify-toniebox-sync#27]
This is in no way an official an endorsement of this project by Boxine, but personally I think it's awesome!

This night, one user sent about 1-2 requests every second which modify a Tonie over and over with the same content without waiting for it to be done transcoding.

For privacy reasons, Boxine does not associate the HTTP user-agent with detailed logging data (we just group it into _android app_, _iOS app_, _other_ for these logs), but based on the extremely high frequency I am certain the user-agent `Apache-HttpClient/4.5.5 (Java/1.8.0_275)` is responsible.

This project should set an HTTP-user agent like `spotify-toniebox-sync (v1.2.3)` so that Boxine can report the bugs to the project causing it. After all, somewhere there is likely a user wondering why their Tonie never finishes transcoding.

**Comment by maximilianvoss** [comment]
Totally valid point. Will add it to: https://github.com/maximilianvoss/toniebox-api/issues/7 as it is part of the API handler which is used.
