### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by heilmic** [maximilianvoss/spotify-toniebox-sync#30]
I think the install instructions are deprecated, at least most of the commands won't work in a newer Ubuntu release. 

Can somebody update them or help me get this thing running?

I hope to get this running, sounds very very cool.

**Comment by andreasfinke57** [comment]
I once fought my way through all the issues and tried a lot. The documentation of the project is not easy for beginners.

I'm running an Ubuntu 20.04 VM and so far I've done the following:

 **Install dependencies:** 
`Sudo apt-get install -y x11vnc xvfb sox lame qdbus-qt5 ffmpeg pulseaudio dbus-x11 xinit git maven`

 **Install JDK 8 as described here:** 

https://docs.datastax.com/en/jdk-install/doc/jdk-install/installOpenJdkDeb.html

 **Install Spotify:** 


```
curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | sudo apt-key add -
echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list

sudo apt-get update && sudo apt-get install spotify-client

```



```

git clone https://github.com/maximilianvoss/spotify-toniebox-sync.git

ln -sf $ PWD / spotify-toniebox-sync / bin / sp / usr / local / bin
ln -sf $ PWD / spotify-toniebox-sync / bin / stream_recorder.pl / usr / local / bin /


```
open the spotify-toniebox-sync folder in the terminal and

`mvn clean install`

everything runs smoothly

https://developer.spotify.com/

create a client there. This gives you a client ID and the client secret. Now into the musicsync.properties file. Add Redirecturl at the same time.
Toniebox access data is also there

Create cache folder and assign appropriate access rights!
Mark musicsync as executable in the folder package / target / output.

I am now only attached to the apicode for spotify. With `./musicsync -–spotify-apicode`, I only get the standard output ...

```

Usage: spotify-toniebox-sync.jar [--daemon | --input INPUT --output OUTPUT]
--daemon
Run in daemon mode to sync periodically all lists in the properties file
--input INPUT
Define an input source for a one-time run
--output OUTPUT
Define an output destination for a one-time run

Input Plugins:
--spotify-apicode
Generate an API Code URL to get attach Application to Spotify Account
--spotify-code CODE
Generate a Refresh token out of the Spotify Code

Output Plugins:
--toniebox-username USERNAME
Set the Toniebox username to login to Toniebox
--toniebox-password PASSWORD
Set the password for the Toniebox user for login
--filesystem-directory DIRECTORY
Set the output path for the files
```






It's getting annoying, but giving up is not.

**Comment by Naatur3** [comment]
Okay, I installed Jdk8 so far everything worked, but from then on the commands no longer work. Cannot install Spotify, etc. Are the commands new? I just want to get the Toniebox Sync right.

**Comment by maximilianvoss** [comment]
fixed with latest version to also support jdk11 and updated the documentation
