### ISSUE TITLE
git clone git@git.voss.rocks:toniebox/spotify-download-service.git asks for a password

### ISSUE THREAD

**Issue by amibuttons** [maximilianvoss/spotify-toniebox-sync#9]
Hello,

how do i clone the donwload-service repository. git asks for a password, which i don't have.

Thank you!

**Comment by erikp152** [comment]
@amibuttons Why is there a reason to clone the repository - you can download every branch-version to make it run, without cloning.

**Comment by maximilianvoss** [comment]
Please try to clone it using https
`
git clone https://github.com/maximilianvoss/spotify-toniebox-sync.git
`
